[workspace]
resolver = "2"

default-run = "panix"

members = [
    "parser",
    "panix",
    "identpool",
    "gc",
]

[workspace.dependencies]
parser = {path = "./parser"}
identpool = {path = "./identpool"}
gc = {path = "./gc"}