[package]
name = "panix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arcstr = "1.1.5"
clap = { version = "4.4.11", features = ["derive"] }
memchr = "2.6.4"
nom = "7.1.3"
