[workspace]
resolver = "2"

default-run = "panix"

members = [
    "parser",
    "panix",
    "identpool",
    "gc",
    "lexer_impedance_matcher",
]

[workspace.dependencies]
parser = {path = "./parser"}
identpool = {path = "./identpool"}
gc = {path = "./gc"}
lexer_impedance_matcher = {path = "./lexer_impedance_matcher"}