[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memchr.workspace = true
lexer_impedance_matcher.workspace = true
gc_derive.workspace = true
thiserror.workspace = true
