[package]
name = "gc_derive"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
gc.workspace = true
syn = {version = "2"}
quote = "1"
proc-macro2 = "1"