[package]
name = "panix"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

default-run = "panix"

[dependencies]
interpreter.workspace = true
gc.workspace = true
clap = { version = "4.4.11", features = ["derive"] }
